### ISSUE TITLE
Dockerfile error

### ISSUE THREAD

**Issue by goodluck-hojae** [songzhen-neu/ADGNN#1]
Hi, I have a couple of issues running the project.

1. I got an error on this line in the Dockerfile.
RUN cd /code/third_party/c-ares \
    && mkdir build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release .. \
    && make install

2. Is there anyway to use the project without building the c++ module?
I can not proceed with running the project. 

Could you please update readme file so that I can possibly replicate the experiment?
It would be really helpful for our team to refer your work.

Thank you.

**Comment by songzhen0210** [comment]
Hi,

Thank you for your interest in our work. We've added the compiled .so files in the cmake/build/ directory to help you run ADGNN without needing to compile C++ code. We hope this makes things easier for you. We’ll be updating our environment configuration and clearing up the README file soon.

**Comment by goodluck-hojae** [comment]
Hi Thank you for your kind updates!
However I was still not able to run the program because of the error I attached
![image](https://github.com/user-attachments/assets/8e98dca4-7d23-4029-8edf-1dab68aeec28)

So I tried to install grpc pybind ( for pybind I had to create third_party directory and install the project there ) protobuf and tried to rebuild them today
It went through building those dependencies however I got an error with cpptest subdirectory error.
![image](https://github.com/user-attachments/assets/81a6b425-5473-44db-9de9-506f619b4992)

Additionally, if I comment out the cpp_test subdirectory in CMakeList, I got the following issue 
![image](https://github.com/user-attachments/assets/2b62ea36-b2d9-49a9-833b-e903c5bc0f1a)


I guess I might be missing something or the project does not have the whole picture to run..
Could you please help me resolving this issue?

Or maybe it could be huge help if I can access docker image via Dockerhub or some other sharing repositories for running the project ( I am leaving my email just in case here (hojaeson@umass.edu) for getting the docker image )

I really appreciate your help.
Thank you.

**Comment by songzhen0210** [comment]
> Hi Thank you for your kind updates! However I was still not able to run the program because of the error I attached ![image](https://private-user-images.githubusercontent.com/8280052/353917876-8e98dca4-7d23-4029-8edf-1dab68aeec28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODgzMTIsIm5iZiI6MTcyMjQ4ODAxMiwicGF0aCI6Ii84MjgwMDUyLzM1MzkxNzg3Ni04ZTk4ZGNhNC03ZDIzLTQwMjktOGVkZi0xZGFiNjhhZWVjMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I2YWY1Y2IxNzhlMmViZDIzYWU0Yjc0N2MwNDIzMzY2N2RmYzZkZDAzODQyYWM5ZjMzOTMxNDM0NDJjZjMyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WFElDXSA6f6aXDKXK0_0UsoueznfucgVFaUesLj54m4)
> 
> So I tried to install grpc pybind ( for pybind I had to create third_party directory and install the project there ) protobuf and tried to rebuild them today It went through building those dependencies however I got an error with cpptest subdirectory error. ![image](https://private-user-images.githubusercontent.com/8280052/353918264-81a6b425-5473-44db-9de9-506f619b4992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODgzMTIsIm5iZiI6MTcyMjQ4ODAxMiwicGF0aCI6Ii84MjgwMDUyLzM1MzkxODI2NC04MWE2YjQyNS01NDczLTQ0ZGItOWRlOS01MDZmNjE5YjQ5OTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRjNmNiNGQ0MWJkODkyY2IzYjk0ZTJlZTFkOTk2NDI2OWIyZWU1ZjllMjUwNDAzY2NhMWE5MmI0YTg1ZjJhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7fkvFTPZpUZ703lbNl7BEz6991jfFATfjVqFepOr2mA)
> 
> Additionally, if I comment out the cpp_test subdirectory in CMakeList, I got the following issue ![image](https://private-user-images.githubusercontent.com/8280052/353922815-2b62ea36-b2d9-49a9-833b-e903c5bc0f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODgzMTIsIm5iZiI6MTcyMjQ4ODAxMiwicGF0aCI6Ii84MjgwMDUyLzM1MzkyMjgxNS0yYjYyZWEzNi1iMmQ5LTQ5YTktODMzYi1lOTAzYzViYzBmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDQ1MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUxZTQ1MzFhMmNkOTZmYzNhNjIyMTI4ODM1Zjc3ZDQ1NWY1ZWIxNjJjN2Y4YzBiNTk5YmM0ZjU4NjQxOTVjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v9ls7w6mJZkPJ3DfhAVujNQtf44Xq-kyQKIraUc3C98)
> 
> I guess I might be missing something or the project does not have the whole picture to run.. Could you please help me resolving this issue?
> 
> Or maybe it could be huge help if I can access docker image via Dockerhub or some other sharing repositories for running the project ( I am leaving my email just in case here ([hojaeson@umass.edu](mailto:hojaeson@umass.edu)) for getting the docker image )
> 
> I really appreciate your help. Thank you.

Hi, 
In the initial version, we missed uploading some compilation and testing files, which may have affected the CMake/Make and Docker compilation processes. We have now uploaded the complete project files and updated the system installation documentation. Thank you for helping us improve the documentation. Moving forward, we will strive to simplify the project configuration process.   

By the way, If you only want to run the code, there's no need to compile the C++ code with CMake and Make. All the C++ code is already integrated into the cmake/build/*.so files. You just need to install the required Python packages and run the script. If you wish to modify the C++ code and compile it yourself,  you can follow the installation document to build the c++ environment for gRPC/protobuf.

I hope this helps you. Thanks again!

**Comment by goodluck-hojae** [comment]
Hi,
Thanks to your help, I was able to build the project successfully.
I still need to talk to my colleagues for running the project as I have a runtime error to process data
For this, I will raise issue if I need your further support.

I sincerely appreciate your help.
Have a good day!
